# Generated by Django 6.0.6 on 2026-06-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discountType', models.CharField(choices=[('FLAT', 'Flat'), ('PERCENTAGE', 'Percentage')], max_length=20)),
                ('discountValue', models.FloatField()),
                ('minCartValue', models.FloatField()),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
